[package]
name = "snarkd_errors"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
colored = { workspace = true }
error-stack = { workspace = true }
thiserror = { workspace = true }
