version: 2.1

# Documentation for the rust orb:
# https://circleci.com/developer/orbs/orb/circleci/rust

orbs:
  # installs protoc
  protobuf: izumin5210/protobuf@0.1.0
  # provides rustfmt, clippy, cargo
  rust: circleci/rust@1.6.0

commands:
  setup:
    description: Sets up the environment for building snarkd
    steps:
      - run:
          name: Install protoc
          command: protobuf/install
      - setup_remote_docker:
          docker_layer_caching: true

jobs:
  lint_and_test:
    description: Runs rustfmt, clippy, and cargo test
    environment:
      RUST_BACKTRACE: 1
    docker:
      - image: cimg/rust:1.64.0
    steps:
      - setup
      - checkout
      - rust/format:
          with_cache: false
      - rust/clippy:
          with_cache: false
      - rust/test:
          with_cache: false
      - save_cache:
            key: 'cargo-<<parameters.cache_version>>-{{ checksum "Cargo.lock" }}'
            paths:
              - ~/.cargo
    parameters:
      cache_version:
        default: v1
        description: Cache version to use - increment this to build a fresh cache.
        type: string

workflows:
  lint_and_test:
    jobs:
      - lint_and_test