version: 2.1

# Documentation for the rust orb:
# https://circleci.com/developer/orbs/orb/circleci/rust

orbs:
  # installs protoc
  protobuf: izumin5210/protobuf@0.1.0
  # provides rustfmt, clippy, cargo
  rust: circleci/rust@1.6.0

commands:
  setup:
    description: Sets up the environment for building snarkd
    parameters:
      protoc:
        default: false
        description: Whether to install protoc during setup
        type: boolean
    steps:
      - when:
          condition: <<parameters.protoc>>
          steps:
            - protobuf/install

jobs:
  # runs rustfmt, clippy, and cargo test
  lint_and_test:
    environment:
      RUST_BACKTRACE: 1
    docker:
      - image: cimg/rust:1.64.0
    steps:
      - setup:
         protoc: true
      - checkout
      - rust/format
      - rust/clippy
      - rust/test

workflows:
  lint_and_test:
    jobs:
      - lint_and_test