[package]
name = "snarkd_peer"
version = "0.1.0"
edition = "2021"


[dependencies]
async-trait = "0.1.58"
bip_bencode = "0.4.4"
hex = "0.4.3"
rand = "0.8.5"
reqwest = { version = "0.11.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.87"
tokio = { version = "1.21.2", features = ["full"] }
url = { version = "2.3.1", features = ["serde"] }
