[package]
name = "snarkd_peer"
version = "0.1.0"
edition = "2021"


[dependencies]
async-trait = "0.1.58"
bip_bencode = "0.4.4"
bip_dht = "0.6.0"
bip_handshake = "0.7.1"
bip_metainfo = "0.12.0"
bip_peer = "0.5.0"
bip_util = "0.5.0"
bip_utracker = "0.4.0"
futures = "0.3.25"
hex = "0.4.3"
lazy_static = "1.4.0"
rand = "0.8.5"
reqwest = { version = "0.11.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.87"
tokio = { version = "1.21.2", features = ["full"] }
tokio-core = "0.1.18"
url = { version = "2.3.1", features = ["serde"] }
