[package]
name = "snarkd_crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bitvec = { workspace = true }
fxhash = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
num-bigint = { workspace = true }
rand = { workspace = true }
rand_xorshift = { workspace = true }
rayon = { workspace = true }
ruint = { workspace = true }
snarkd_common = { workspace = true }
thiserror = { workspace = true }
