[package]
name = "snarkd_common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
smallvec = { workspace = true }
hex = { workspace = true }
prost = { workspace = true }