[package]
name = "test-runner"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[dependencies]
colored.workspace = true
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
walkdir = { workspace = true }
