[package]
name = "snarkd_network"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.10"
async-trait = "0.1"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
dashmap = "5.4"

snarkd_common = { path = "../snarkd_common" }

[build-dependencies]
prost-build = "0.10"
