[package]
name = "snarkd_eval"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
indexmap = { workspace = true }
snarkd_crypto = { workspace = true }
snarkd_ir = { workspace = true }
