name: Lint and Test
on: [push]
env:
  RUST_BACKTRACE: 1
jobs:
  lint_and_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Test
        run: cargo test --all